# Generated by Django 3.1.7 on 2021-04-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('open_time', models.TimeField(default='00:00:00')),
                ('close_time', models.TimeField(default='00:00:00')),
                ('holiday', models.CharField(choices=[('Monday', '월요일'), ('Tuesday', '화요일'), ('Wednesday', '수요일'), ('Thursday', '목요일'), ('Friday', '금요일'), ('Saturday', '토요일'), ('Sunday', '일요일'), ('null', '휴일없음')], default='null', max_length=16)),
                ('meeting_time', models.DateField(blank=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('content', models.TextField(blank=True)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
                ('image5', models.ImageField(upload_to='')),
                ('kakaomap_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
