# Generated by Django 3.1.7 on 2021-06-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_auto_20210512_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='image5',
        ),
        migrations.AddField(
            model_name='cafe',
            name='allow_pat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='desert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='discount_pruncup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='no_plasticCup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='no_straw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='pruncup_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='use_biodegradable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
    ]
